/* List of defines generated by configure. Included with preprocessor flag,
 * -include, to avoid long list of -D defines on the compile command-line.
 * Do not edit.
 */

#ifndef _JS_CONFDEFS_H_
#define _JS_CONFDEFS_H_

#define AVMPLUS_IA32 1
#define AVMPLUS_WIN32 1
#define CPP_THROW_NEW throw()
#define D_INO d_ino
#define FEATURE_NANOJIT 1
#define HAVE_ATLBASE_H 1
#define HAVE_GETSYSTEMTIMEASFILETIME 1
#define HAVE_MMINTRIN_H 1
#define HAVE_OLEACC_IDL 1
#define HAVE_SNPRINTF 1
#define HAVE_SYSTEMTIMETOFILETIME 1
#define HAVE_WPCAPI_H 1
#define HW_THREADS 1
#define JS_HAVE___INTN 1
#define JS_STDDEF_H_HAS_INTPTR_T 1
#define JS_TRACER 1
#define JS_THREADSAFE 1
#define MOZ_DLL_SUFFIX ".dll"
#define NEW_H <new>
#define NO_X11 1
#define STDC_HEADERS 1
#define WIN32 1
#define WIN32_LEAN_AND_MEAN 1
#define WINVER 0x500
#define XP_WIN 1
#define XP_WIN32 1
#define X_DISPLAY_MISSING 1
#define _CRT_NONSTDC_NO_WARNINGS 1
#define _CRT_SECURE_NO_WARNINGS 1
#define _WIN32_IE 0x0500
#define _WIN32_WINNT 0x500
#define _WINDOWS 1
#define _X86_ 1

#endif /* _JS_CONFDEFS_H_ */

