.TH FLUSSPFERD 1 "April 2009"
.SH NAME
flusspferd \- interactive Javascript shell/repl
.SH SYNOPSIS
.B flusspferd [option] ... [
.I file
.B |-] [arg] ...
.SH DESCRIPTION
flusspferd is an interactive Javascript shell/repl based on the Flusspferd
Javascript library. It can be used to run and test Javascript code.
.SH OPTIONS
.IP -h
Displays a help message
.IP "-c config-file"
Loads config from file
.I config-file
.IP -i
Enter interactive mode (after files)
.IP -O
Machine command mode (separator '\\0')
.IP "-f file"
run this file before standard script handling
.IP --
stop processing arguments
.SH AUTHOR
Flusspferd Team <team -AT- flusspferd -DOT- org>
